mode = "sequential"

[genotype]
inputs = 3
nodes = 10
outputs = 1
parameters = 2
connections = 2

[library]
output_type = "Array"

[endpoint]
name = "no_endpoint"

[library.primitives]
0 = "f_max"
1 = "f_min"
2 = "f_mean"
3 = "f_add"
4 = "f_sub"
5 = "f_bitwise_not"
6 = "f_bitwise_or"
7 = "f_bitwise_and"
8 = "f_bitwise_and_mask"
9 = "f_bitwise_xor"
10 = "f_sqrt"
11 = "f_pow"
12 = "f_exp"
13 = "f_log"
14 = "f_median_blur"
15 = "f_gaussian_blur"
16 = "f_laplacian"
17 = "f_sobel"
18 = "f_roberts"
19 = "f_canny"
20 = "f_sharpen"
21 = "f_gabor"
22 = "f_diff_gaussian"
23 = "f_absdiff"
24 = "f_fluo_tophat"
25 = "f_relative_diff"
26 = "f_erode"
27 = "f_dilate"
28 = "f_open"
29 = "f_close"
30 = "f_morph_gradient"
31 = "f_morph_tophat"
32 = "f_morph_blackhat"
33 = "f_fill"
34 = "f_remove_small_objects"
35 = "f_remove_small_holes"
36 = "f_threshold"
37 = "f_threshold_at_1"
38 = "f_distance_transform"
39 = "f_distance_transform_thresh"
40 = "f_bin_inrange"
41 = "f_inrange"
