name: Dev Workflow

on:
  push:
    branches: [ dev-* ]
  pull_request:
    branches: [ dev-* ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Run quick tests
      run: |
        uv run python tests/test_runner.py --quick

    - name: Check code formatting
      run: |
        uv run ruff format --check src/ tests/

    - name: Lint with auto-fix
      run: |
        uv run ruff check --fix src/ tests/